#!/bin/bash

export DISPLAY=:0

rm -r /tmp/.X11-unix 2> /dev/null

# https://github.com/balena-labs-projects/xserver/issues/16
DISPLAY_NR=$(echo "$DISPLAY" | sed "s/://")
LOCKFILE="/tmp/.X${DISPLAY_NR}-lock"
[ -f "$LOCKFILE" ] && rm -f "$LOCKFILE"

export DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket

startx -- $DISPLAY -nocursor
