#!/bin/sh

glxgears > /dev/null &
ffplay sample.mp4 -loop -1 -window_title "sample-video" 2> /dev/null &

feh \
    --no-fehbg \
    --image-bg black \
    --bg-scale ~/kermit.jpg

exec ../zig-out/bin/ExtendedWM
