#!/bin/bash

export DISPLAY=:0
export UDEV=1
export DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket

[ -f "/usr/bin/entry.sh" ] && /usr/bin/entry.sh echo "ExtendedWM - Extended Window Manager"

# Raspberry Pi 5 GPU driver configuration
if [ "${BALENA_DEVICE_TYPE}" = "raspberrypi5" ]; then
    echo "Raspberry Pi 5 detected, injecting X11 configuration"
    cp -a "/99-vc4.conf" "/etc/X11/xorg.conf.d/"
fi

rm -r /tmp/.X11-unix 2> /dev/null

# https://github.com/balena-labs-projects/xserver/issues/16
DISPLAY_NR=$(echo "$DISPLAY" | sed "s/://")
LOCKFILE="/tmp/.X${DISPLAY_NR}-lock"
[ -f "$LOCKFILE" ] && rm -f "$LOCKFILE"

if [ "$CURSOR_ENABLED" = "1" ]; then
    startx -- $DISPLAY
else
    startx -- $DISPLAY -nocursor
fi
